import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
export default function Home() {
  const session = useSession();
  console.log(session);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!session.data && (
        <button
          onClick={() => {
            console.log("Signin");
            signIn();
          }}
        >
          Signup
        </button>
      )}
      {session.data && <button onClick={signOut}>SignOut</button>}
    </div>
  );
}
